# Site settings
title: DATA 515a - Software Development for Data Scientists
email: jlheller -- AT -- uw.edu
description: "UW course, Software Development for Data Scientists"
url: "http://uwseds.github.io"
twitter_username: uwescience
github_username:  UWSEDS


# Build settings
markdown: kramdown
