# Site settings
title: CSE 599 B1 - Sofware Engineering for Data Scientists
email: jakevdp -- AT -- uw.edu
description: "2016 UW course, Software Engineering for Data Scientists"
url: "http://uwseds.github.io"
twitter_username: uwescience
github_username:  UWSEDS


# Build settings
markdown: kramdown
